const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => [...document.querySelectorAll(sel)];
const lessons = window.PP_LESSONS;
const STORE_KEY = "prepython-mini-game-studio:v1";
const state = loadState();
let lessonIndex = state.currentLesson || 0;
let worker = null, runSeq = 0, activeRun = 0, timeoutId = 0, hintShown = 0, importPayload = null, timerId = 0, timerLeft = 5400;
const pending = new Map();

function blankState(){
  return {schema:1,curriculum:"prepython-2026-10-10",workspaceId:crypto.randomUUID?.() || String(Date.now()),lang:"th",mode:"practice",reduceMotion:false,currentLesson:0,lessons:{},portfolio:[]};
}
function loadState(){try{const raw=localStorage.getItem(STORE_KEY);if(!raw)return blankState();const parsed=JSON.parse(raw);if(parsed.schema!==1)throw new Error("unsupported");return {...blankState(),...parsed};}catch{return blankState();}}
function saveState(label="Saved"){try{localStorage.setItem(STORE_KEY,JSON.stringify(state));$("#saveState").textContent=label;$("#saveState").className="badge";}catch{$("#saveState").textContent="Storage unavailable - export now";$("#saveState").className="badge soft";}}
function lessonState(id){state.lessons[id] ||= {code:null,inputs:null,prediction:"",reflection:"",hintLevel:0,evidence:null,testsStale:true,rubric:{behavior:0,change:0,explain:0,debug:0},review:null};return state.lessons[id];}
function t(key){return (window.PP_I18N[state.lang]||window.PP_I18N.th)[key]||key}
function textFor(lesson, stem){return state.lang==="en" ? (lesson[stem+"En"]||lesson[stem+"Th"]) : (lesson[stem+"Th"]||lesson[stem+"En"])}

function init(){
  bindStatic();
  paintI18n();
  paintHome();
  paintLesson();
  setMode(state.mode);
  startRuntime();
}
function bindStatic(){
  $("#startBtn").onclick=()=>{lessonIndex=0;state.currentLesson=0;setMode("practice");paintLesson();saveState();};
  $("#continueBtn").onclick=()=>{lessonIndex=state.currentLesson||0;setMode("practice");paintLesson();};
  $("#modeSelect").onchange=e=>setMode(e.target.value);
  $("#langToggle").onclick=()=>{state.lang=state.lang==="th"?"en":"th";document.documentElement.lang=state.lang;paintI18n();paintHome();paintLesson();saveState();};
  $("#motionToggle").onchange=e=>{state.reduceMotion=e.target.checked;document.body.classList.toggle("reduce-motion",state.reduceMotion);saveState();};
  $("#runBtn").onclick=()=>runCurrent();
  $("#stopBtn").onclick=stopRun;
  $("#retryRuntimeBtn").onclick=()=>{if(worker)worker.terminate();startRuntime();};
  $("#checkBtn").onclick=runChecks;
  $("#copyBtn").onclick=()=>navigator.clipboard?.writeText($("#codeEditor").value);
  $("#downloadPyBtn").onclick=()=>downloadFile(currentLesson().py,$("#codeEditor").value,"text/x-python;charset=utf-8");
  $("#resetCodeBtn").onclick=()=>{if(confirm("Restore starter code for this lesson?")){const l=currentLesson(),ls=lessonState(l.id);ls.code=l.starter;ls.testsStale=true;paintLesson();saveState("Saved reset");}};
  $("#saveEvidenceBtn").onclick=saveEvidence;
  $("#teacherReviewBtn").onclick=teacherReview;
  $("#nextHintBtn").onclick=()=>{hintShown++;renderHints();lessonState(currentLesson().id).hintLevel=Math.max(lessonState(currentLesson().id).hintLevel,hintShown);saveState();};
  $("#exportAllBtn").onclick=exportBackup;
  $("#parentReportBtn").onclick=parentReport;
  $("#finalPackageBtn").onclick=finalPackage;
  $("#clearDataBtn").onclick=clearData;
  $("#importInput").onchange=readImport;
  $("#confirmImportBtn").onclick=confirmImport;
  $("#cancelImportBtn").onclick=()=>$("#importDialog").close();
  $("#stagePrev").onclick=()=>stageStep(-1);
  $("#stageNext").onclick=()=>stageStep(1);
  $("#stagePlay").onclick=playStage;
  $("#loadBridgeBtn").onclick=loadBridgeExample;
  $("#timerStart").onclick=toggleTimer;
  $("#timerReset").onclick=()=>{timerLeft=5400;paintTimer();};
  ["codeEditor","inputQueue","predictionText","reflectionText","teacherReason"].forEach(id=>$("#"+id).addEventListener("input",draftChanged));
}
function currentLesson(){return lessons[lessonIndex]}
function draftChanged(){const l=currentLesson(),ls=lessonState(l.id);ls.code=$("#codeEditor").value;ls.inputs=$("#inputQueue").value;ls.prediction=$("#predictionText").value;ls.reflection=$("#reflectionText").value;ls.testsStale=true;ls.bridgeActive=!!(l.bridgeCode&&ls.bridgeActive);if(ls.evidence)ls.currentEvidenceStatus="stale-after-edit";$("#visualStage")._lastRun=null;renderStage(0);$("#evidenceState").textContent=ls.evidence?"Checks stale after edit":"Exploring";saveState("Saved draft");}

function paintI18n(){
  $$("[data-i18n]").forEach(el=>{el.textContent=t(el.dataset.i18n)});
  $("#modeSelect").value=state.mode;$("#motionToggle").checked=state.reduceMotion;document.body.classList.toggle("reduce-motion",state.reduceMotion);
}
function setMode(mode){state.mode=mode;$("#modeSelect").value=mode;$("#homePanel").hidden=mode!=="home"&&mode!=="practice"?true:false;$("#workspacePanel").hidden=mode==="portfolio";$("#portfolioPanel").hidden=mode!=="portfolio";$("#teacherPanel").hidden=mode!=="teacher";if(mode==="portfolio")paintPortfolio();saveState();}
function paintHome(){
  $("#lessonMap").className="map-grid";$("#lessonMap").innerHTML="";
  lessons.forEach((lesson,i)=>{const ls=lessonState(lesson.id);const b=document.createElement("button");b.className="map-stop"+(ls.evidence?" done":"")+(i===lessonIndex?" current":"");b.innerHTML=`<span class="eyebrow">${i+1} · 90 min</span><strong>${textFor(lesson,"title")}</strong><span>${lesson.product}</span>`;b.onclick=()=>{lessonIndex=i;state.currentLesson=i;setMode("practice");paintLesson();};$("#lessonMap").appendChild(b);});
}
function paintLesson(){
  const lesson=currentLesson(), ls=lessonState(lesson.id); hintShown=ls.hintLevel||0;
  $("#lessonTabs").innerHTML="";lessons.forEach((l,i)=>{const b=document.createElement("button");b.textContent=`${i+1}. ${textFor(l,"title")}`;b.className=i===lessonIndex?"primary":"";b.onclick=()=>{lessonIndex=i;state.currentLesson=i;paintLesson();saveState();};$("#lessonTabs").appendChild(b);});
  $("#lessonKicker").textContent=`Session ${lessonIndex+1} · 90 minutes · ${lesson.product}`;
  $("#lessonTitle").textContent=textFor(lesson,"title");$("#lessonObjective").textContent=textFor(lesson,"objective");
  $("#codeEditor").value=ls.code ?? initialCodeForLesson(lesson);$("#inputQueue").value=ls.inputs ?? initialInputsForLesson(lesson);$("#predictionText").value=ls.prediction||"";$("#reflectionText").value=ls.reflection||"";$("#teacherReason").value=ls.review?.reason||"";
  $("#challengeText").textContent=textFor(lesson,"challenge");$("#criteriaList").innerHTML=lesson.criteria.map(c=>`<li>${escapeHtml(c)}</li>`).join("");
  $("#misconceptionText").textContent=lesson.misconception;$("#exitCheckText").textContent=lesson.exit;
  $("#evidenceState").textContent=ls.review?.status || (ls.evidence ? (ls.testsStale?"Checks stale after edit":(ls.evidence.trust==="imported"?"Imported evidence pending rerun":"Artifact saved")) : "Not started");
  renderAgenda();renderRubric();renderHints();renderLessonDetails();renderStage(0);paintHome();
}
function initialCodeForLesson(lesson){if(lesson.id==="lesson08"){const prior=lessonState("lesson07").evidence?.sourceVersion?.code||lessonState("lesson07").lastChecks?.source;if(prior)return prior;return window.PP_LESSONS.find(l=>l.id==="lesson07").starter;}return lesson.starter;}
function initialInputsForLesson(lesson){if(lesson.id==="lesson08"){const priorInputs=lessonState("lesson07").evidence?.inputs||lessonState("lesson07").lastChecks?.results?.find(r=>r.inputs?.length)?.inputs?.join("\n");return priorInputs||"2\n0\n6";}return lesson.inputs;}
function renderAgenda(){const total=currentLesson().agenda.reduce((s,a)=>s+a[1],0);$("#agendaList").innerHTML=currentLesson().agenda.map(a=>`<div class="agenda-item"><strong>${a[1]} min</strong><br>${escapeHtml(a[0])}</div>`).join("")+`<div class="agenda-item"><strong>Total</strong><br>${total} min</div>`;}
function renderHints(){const l=currentLesson();$("#hintList").innerHTML=l.hints.map((h,i)=>`<li class="${i<hintShown?'':'locked'}">${i<hintShown?escapeHtml(h):"ขอตัวช่วยเพื่อเปิด / Ask for hint"}</li>`).join("");}
function renderRubric(){const lesson=currentLesson(), ls=lessonState(lesson.id);const names={behavior:"Program behavior",explain:"Explanation",transfer:"Transfer / intentional change",testing_debugging:"Testing and debugging"};$("#rubricGrid").innerHTML=Object.keys(names).map(k=>`<div class="rubric-row"><span>${names[k]}${rubricAnchor(lesson,k)?`<p class="rubric-anchor">${escapeHtml(rubricAnchor(lesson,k))}</p>`:""}</span><select data-rubric="${k}"><option>0</option><option>1</option><option>2</option></select></div>`).join("");$$("[data-rubric]").forEach(s=>{s.value=ls.rubric[s.dataset.rubric]||0;s.onchange=()=>{ls.rubric[s.dataset.rubric]=Number(s.value);saveState();};});}
function rubricAnchor(lesson,k){const r=lesson.rubricAnchors||{};return r[k]||({transfer:r.change,testing_debugging:r.debug,explain:r.explanation}[k])||"";}
function renderLessonDetails(){const l=currentLesson();$("#lineExplanationList").innerHTML=renderLineExplanations(l);$("#activityPathList").innerHTML=renderTaskCards(l);$("#loadBridgeBtn").hidden=!l.bridgeCode;$("#loadBridgeBtn").textContent=state.lang==="en"?(lessonState(l.id).bridgeActive?"Restore main draft":"Load variable-argument bridge"):(lessonState(l.id).bridgeActive?"คืน draft หลัก":"โหลด bridge ตัวแปรเป็น argument");const scaffold=l.scaffold?.[state.lang]||l.scaffold?.th||[];$("#supportStretchBox").innerHTML=`<strong>Scaffold</strong><ul>${scaffold.map(x=>`<li>${escapeHtml(x)}</li>`).join("")||"<li>Pending.</li>"}</ul><strong>Stretch</strong><p>${escapeHtml((l.stretch&&(state.lang==="en"?l.stretch.en:l.stretch.th))||"Pending.")}</p><details><summary>${state.lang==="en"?"Teacher exit key":"เฉลย Exit สำหรับครู"}</summary><p>${escapeHtml(l.exitAnswer?.[state.lang]||l.exitAnswer?.th||"Pending teacher key.")}</p></details>`;$("#debugExampleBox").textContent=l.debugTask?.code||"Debug artifact pending for this lesson.";$("#debugPromptText").textContent=(l.debugTask&&(state.lang==="en"?l.debugTask.promptEn:l.debugTask.promptTh))||"Debug prompt pending for this lesson.";}
function renderLineExplanations(l){const codeLines=$("#codeEditor").value.split(/\r?\n/);return (l.lineExplanations||[]).map(x=>{const expected=x.exactCode??(l.referenceCode||l.starter||"").split(/\r?\n/)[x.line-1];const actual=codeLines[x.line-1];const fresh=expected==null||actual===expected;const note=fresh?"":(state.lang==="en"?"mapping stale after edit":"คำอธิบายนี้ผูกกับโค้ดอ้างอิง ไม่ใช่บรรทัดที่แก้แล้ว");return `<li><strong>Line ${x.line}</strong> ${fresh?"":"<span class=\"badge soft\">stale</span>"} ${escapeHtml(state.lang==="en"?x.en:x.th)}${note?`<p class="rubric-anchor">${escapeHtml(note)}</p>`:""}</li>`;}).join("")||"<li>Detailed line explanations are pending for this lesson.</li>";}
function renderTaskCards(l){const tasks=l.tasks||tasksFromActivityPath(l);if(!tasks.length)return "<p>Activity path content is pending source review for this lesson.</p>";return tasks.map(task=>`<section class="activity-step"><strong>${escapeHtml(task.label[state.lang]||task.label.th)}</strong><p>${escapeHtml(task.instruction[state.lang]||task.instruction.th)}</p><ul>${(task.successChecks?.[state.lang]||task.successChecks?.th||[]).map(x=>`<li>${escapeHtml(x)}</li>`).join("")}</ul><details><summary>${state.lang==="en"?"Teacher key / reveal":"เฉลยครู / เปิดเมื่อพร้อม"}</summary><p>${escapeHtml(task.teacherKey?.[state.lang]||task.teacherKey?.th||"No teacher key supplied.")}</p></details></section>`).join("");}
function tasksFromActivityPath(l){return (l.activityPath||[]).filter(x=>["worked","guided","independent"].includes(x.phase)).map(x=>({label:{th:x.phase,en:x.phase},instruction:{th:x.th,en:x.en},successChecks:{th:l.criteria,en:l.criteria},teacherKey:{th:"ใช้เป็นคำชวนคิดสำหรับครู ไม่ใช่คำตอบอัตโนมัติ",en:"Teacher prompt only; not an automatic student answer."}}));}
function loadBridgeExample(){const l=currentLesson(),ls=lessonState(l.id);if(!l.bridgeCode)return;if(ls.bridgeActive){$("#codeEditor").value=ls.primaryCodeBeforeBridge||ls.code||l.starter;ls.bridgeActive=false;draftChanged();return;}ls.primaryCodeBeforeBridge=$("#codeEditor").value;$("#codeEditor").value=l.bridgeCode;ls.bridgeActive=true;draftChanged();$("#evidenceState").textContent="Bridge example loaded; checks use bridge evidence until restored.";}

function startRuntime(){
  try{worker=new Worker("js/python-worker.js");}catch(e){$("#runtimeStatus").textContent="Runtime unavailable: worker could not start";return;}
  worker.onmessage=e=>{const m=e.data;if(m.type==="ready"){$("#runtimeStatus").textContent="Mode A: real Python execution ready ("+m.version+")";$("#runState").textContent="Ready";}if(m.type==="status"){$("#runtimeStatus").textContent=m.status;}if(m.type==="unavailable"){$("#runtimeStatus").textContent="Python runtime unavailable. External editor fallback required. "+m.error;}if(m.type==="result")handleRunResult(m);if(m.type==="astResult")handleAstResult(m);};
}
function parseInputs(){const raw=$("#inputQueue").value;if(raw==="")return [];return raw.split(/\r?\n/).map(line=>line==="<empty>"?"":line);}
function runCurrent(){if(!worker)return;const code=$("#codeEditor").value, inputs=parseInputs(), id=++runSeq, sourceHash=hash(code);activeRun=id;$("#runState").textContent="Running";$("#runBtn").disabled=true;$("#stopBtn").disabled=false;$("#outputBox").textContent="";$("#inputTranscript").textContent="";worker.postMessage({type:"run",runId:id,code,inputs});timeoutId=setTimeout(()=>{if(activeRun===id)stopRun("Timeout after 5 seconds; worker restarted.");},5000);pending.set(id,{kind:"interactive",lessonId:currentLesson().id,code,inputs,sourceHash,startedAt:new Date().toISOString(),mode:state.mode});}
function stopRun(msg="Stopped. Runtime memory restarted; code was kept."){if(worker)worker.terminate();clearTimeout(timeoutId);for(const [id,item] of pending){if(item.resolve)item.resolve({stdout:"",stderr:"",error:"Timeout: worker restarted",inputs:[],timedOut:true,runId:id});}pending.clear();activeRun=0;$("#runState").textContent=msg;$("#runBtn").disabled=false;$("#stopBtn").disabled=true;startRuntime();}
function handleRunResult(m){const meta=pending.get(m.runId);if(meta?.resolve){pending.delete(m.runId);meta.resolve({...m,meta});return;}if(m.runId!==activeRun||!meta)return;pending.delete(m.runId);clearTimeout(timeoutId);const runRecord={at:new Date().toISOString(),runId:m.runId,lessonId:meta.lessonId,stdout:m.stdout||"",stderr:m.stderr||"",error:m.error||"",inputs:m.inputs||[],vars:m.vars||{},source:meta.code,sourceHash:meta.sourceHash,runtime:"Pyodide 0.26.4"};const dispatchedIsOpen=meta.lessonId===currentLesson().id&&hash($("#codeEditor").value)===meta.sourceHash;if(dispatchedIsOpen){$("#runBtn").disabled=false;$("#stopBtn").disabled=true;$("#runState").textContent=m.error?"Error":"Finished";$("#outputBox").textContent=(m.stdout||"")+(m.stderr||"")+(m.error?("\n"+friendlyError(m.error)):"");$("#inputTranscript").textContent=(m.inputs||[]).map(x=>`${x.index}. ${x.prompt}${JSON.stringify(x.value)}`).join("\n");renderStage(0,{...m,record:runRecord});}else{$("#runBtn").disabled=false;$("#stopBtn").disabled=true;}
  const ls=lessonState(meta.lessonId);if(meta.mode!=="teacher"){ls.lastRun=runRecord;saveState(dispatchedIsOpen?"Saved":"Saved dispatched run; current screen unchanged");}else if(dispatchedIsOpen){$("#runState").textContent += " · teacher demo not saved to learner evidence";}}
function friendlyError(err){if(err.includes("ValueError"))return "ValueError: int แปลงข้อความนี้เป็นเลขไม่ได้ / int cannot convert this text.";if(err.includes("EOFError"))return "EOFError: input ไม่พอ เพิ่มบรรทัดใน input queue แล้วรันใหม่.";if(err.includes("NameError"))return "NameError: ชื่อนี้ยังไม่มีค่า หรือสะกดตัวพิมพ์เล็กใหญ่ไม่ตรง.";if(err.includes("IndentationError"))return "IndentationError: ตรวจจำนวนช่องว่างหน้าบรรทัดใน block.";if(err.includes("SyntaxError"))return "SyntaxError: ตรวจเครื่องหมาย quote, วงเล็บ, colon.";return err;}

async function runChecks(){const lesson=currentLesson(), lessonId=lesson.id, code=$("#codeEditor").value, sourceHash=hash(code), testSuiteVersion=`${lesson.id}:2026-10-10`, lsForSuite=lessonState(lessonId), suite=(lsForSuite.bridgeActive&&lesson.bridgeTests)?lesson.bridgeTests:lesson.tests, assessmentMode=(suite===lesson.bridgeTests?"bridge":"challenge");const results=[];$("#checkBtn").disabled=true;try{for(const spec of suite){const expanded=expandDynamicTest(spec,code);if(expanded.kind==="ast"){const ok=await astRoundtrip(code,expanded,sourceHash,lessonId);results.push({name:expanded.name,ok:!!ok.ok,detail:ok.error||(!ok.ok?"required construct not found":""),sourceHash,assessmentMode});continue;}const testCode=code, testHash=sourceHash;const out=await runOne(testCode,expanded.inputs||[],testHash,lessonId);let ok=false,detail="";const actualStdout=normalizeOut(out.stdout||""), expectedStdout=normalizeOut(expanded.exactStdout||"");const hasRuntimeError=!!out.error;if(expanded.expectError){ok=(out.error||"").includes(expanded.expectError);detail=ok?`raised ${expanded.expectError}`:`expected ${expanded.expectError}`;}else if(hasRuntimeError){ok=false;detail=friendlyError(out.error||"Runtime error");}else if(expanded.exactStdout){ok=actualStdout===expectedStdout;detail=ok?"exact stdout matched":`expected ${JSON.stringify(expectedStdout)}, got ${JSON.stringify(actualStdout)}`;}else if(expanded.expectIncludes){ok=(out.stdout||"").includes(expanded.expectIncludes);detail=ok?"included expected text":"missing expected text";}else if(expanded.kind==="stdoutMinLines"){ok=(out.stdout||"").trim().split(/\n/).filter(Boolean).length>=expanded.min;}else if(expanded.kind==="count"){ok=((out.stdout||"").match(new RegExp(escapeReg(expanded.text),"g"))||[]).length===expanded.count;}else if(expanded.expectLastScore!=null){const scores=[...(out.stdout||"").matchAll(/Score:\s*([-\d]+)/g)].map(m=>Number(m[1]));ok=scores[scores.length-1]===expanded.expectLastScore;detail=`last score ${scores[scores.length-1]} expected ${expanded.expectLastScore}`;}if(expanded.requiredPoints&&expanded.detectedPoints!==expanded.requiredPoints){ok=false;detail=`change score increment to ${expanded.requiredPoints}; detected ${expanded.detectedPoints}`;}if(out.timedOut){ok=false;detail="Timeout; worker restarted";}results.push({name:expanded.name,ok,detail,inputs:expanded.inputs||[],stdout:out.stdout||"",error:out.error||"",runId:out.runId,sourceHash:testHash,expected:expanded.exactStdout??expanded.expectLastScore??expanded.expectIncludes??expanded.expectError??"",assessmentMode});}}finally{$("#checkBtn").disabled=false;}
  const currentMatches=lessonId===currentLesson().id&&hash($("#codeEditor").value)===sourceHash;$("#checkResults").innerHTML=results.map(r=>`<p class="${r.ok?'result-pass':'result-fail'}">${r.ok?'PASS':'TRY AGAIN'} · ${escapeHtml(r.assessmentMode==="bridge"?"Bridge: ":"")}${escapeHtml(r.name)} ${escapeHtml(r.detail||"")}</p>`).join("");const ls=lessonState(lesson.id);const record={at:new Date().toISOString(),runtime:"Pyodide 0.26.4",testSuiteVersion,assessmentMode,results,source:code,sourceHash};ls.checkHistory=[...(ls.checkHistory||[]),record].slice(-8);if(currentMatches){ls.lastChecks=record;ls.testsStale=false;$("#evidenceState").textContent=results.every(r=>r.ok)?(assessmentMode==="bridge"?"Bridge checks passed; main challenge preserved separately":"Core behavior checks passed"):"Exploring";}else{ls.testsStale=true;$("#evidenceState").textContent="Checks completed for earlier source; current code is stale";}saveState(currentMatches?"Saved checks":"Saved snapshot checks; current code stale");}
function runOne(code,inputs,sourceHash,lessonId){return new Promise(resolve=>{const id=++runSeq;pending.set(id,{kind:"check-run",lessonId,code,inputs,sourceHash,resolve,startedAt:new Date().toISOString(),mode:state.mode});worker.postMessage({type:"run",runId:id,code,inputs});setTimeout(()=>{if(pending.has(id)){pending.delete(id);stopRun("Check timeout after 5 seconds; worker restarted.");resolve({stdout:"",stderr:"",error:"Timeout",inputs:[],timedOut:true,runId:id});}},5500);});}
function astRoundtrip(code,spec,sourceHash,lessonId){return new Promise(resolve=>{const id=++runSeq;pending.set(id,{kind:"ast",lessonId,code,sourceHash,resolve,startedAt:new Date().toISOString(),mode:state.mode});worker.postMessage({type:"ast",runId:id,code,spec});setTimeout(()=>{if(pending.has(id)){pending.delete(id);resolve({ok:false,error:"AST timeout",runId:id});}},5500);});}
function handleAstResult(m){const meta=pending.get(m.runId);if(!meta)return;pending.delete(m.runId);if(meta.resolve)meta.resolve(m);}
function expandDynamicTest(spec,code){if(spec.kind!=="dynamicScore")return spec;const multiplier=detectMultiplier(code);const points=detectPoints(code);const requiredPoints=spec.requirePoints||points;const correct=[1,2,3].map(n=>String(n*multiplier));let answers=correct;if(spec.pattern==="wrong")answers=["0","0","0"];if(spec.pattern==="mixed")answers=[correct[0],"0",correct[2]];const asksAvatar=code.includes("avatar = input") || code.includes("avatar=input");const inputs=(spec.withAvatar&&asksAvatar)?[spec.avatar||"Nori",...answers]:answers;const correctCount=spec.pattern==="wrong"?0:spec.pattern==="mixed"?2:3;return {...spec,kind:"scoreCase",inputs,expectLastScore:correctCount*requiredPoints,requires:`points per correct answer = ${requiredPoints}`,name:`${spec.name} (multiplier ${multiplier}, expected points ${requiredPoints}, detected points ${points})`,detectedPoints:points,requiredPoints};}

function saveEvidence(){const l=currentLesson(), ls=lessonState(l.id), code=$("#codeEditor").value, sourceHash=hash(code);const checksMatch=ls.lastChecks?.sourceHash===sourceHash&&!ls.testsStale;const record={trust:"local",at:new Date().toISOString(),kind:ls.bridgeActive?"bridge":"challenge",sourceVersion:{hash:sourceHash,code},inputs:$("#inputQueue").value,prediction:$("#predictionText").value,reflection:$("#reflectionText").value,lastRun:ls.lastRun?.sourceHash===sourceHash?ls.lastRun:null,lastChecks:checksMatch?ls.lastChecks:null,hintLevel:ls.hintLevel||0,rubric:{...ls.rubric},reviewPending:true};if(ls.bridgeActive){ls.bridgeEvidence=record;$("#evidenceState").textContent=checksMatch?"Bridge evidence saved":"Bridge evidence saved; checks pending";saveState("Saved bridge evidence");return;}ls.evidence=record;state.portfolio=state.portfolio.filter(p=>p.lessonId!==l.id);state.portfolio.push({lessonId:l.id,title:textFor(l,"title"),product:l.product,evidence:ls.evidence,bridgeEvidence:ls.bridgeEvidence||null});$("#evidenceState").textContent=checksMatch?"Artifact saved":"Artifact saved; current checks pending";saveState("Saved evidence");paintPortfolio();}
function teacherReview(){const ls=lessonState(currentLesson().id), reason=$("#teacherReason").value.trim(), rubric=ls.rubric||{}, values=["behavior","explain","transfer","testing_debugging"].map(k=>Number(rubric[k]??(k==="transfer"?rubric.change:k==="testing_debugging"?rubric.debug:0))), behavior=Number(rubric.behavior||0), sum=values.reduce((a,b)=>a+b,0), checksOk=ls.lastChecks?.results?.every(r=>r.ok)&&ls.lastChecks.sourceHash===hash($("#codeEditor").value)&&!ls.testsStale;if(!reason)return alert("Teacher review needs a brief reason.");if(!(checksOk&&sum>=6&&behavior===2&&values.every(v=>v>0)))return alert("Review cannot mark demonstrated yet: need current passing checks, rubric total >= 6, behavior = 2, and no dimension = 0.");ls.review={status:"Teacher reviewed: demonstrated",reason,at:new Date().toISOString(),rubric:{...rubric},sourceHash:hash($("#codeEditor").value),basis:"local teacher annotation with current checks"};$("#evidenceState").textContent=ls.review.status;saveState("Saved review");}

function renderStage(step=0, run=null){const l=currentLesson();const active=run||$("#visualStage")._lastRun||null;const runIsFresh=active?.record&&active.record.lessonId===l.id&&active.record.sourceHash===hash($("#codeEditor").value);const stageRun=run?run:(runIsFresh?active:null);const events=stageEvents(l,stageRun);step=Math.max(0,Math.min(events.length-1,step));$("#visualStage").dataset.step=step;$("#visualStage").dataset.maxStep=events.length-1;$("#visualStage")._lastRun=stageRun;const title=textFor(l,"title"), ev=events[step];$("#visualStage").innerHTML=`<div class="arcade-machine"><div class="marquee">${escapeHtml(title)}</div><div class="concept-row">${stageCells(l,ev,stageRun)}</div><div><div class="arrowline"></div><strong>${ev.kind==="authored"?"Authored demo visualization":"Run-linked teaching visualization"}:</strong> ${escapeHtml(ev.summary)}</div></div>`;$("#stageSummary").textContent=ev.summary;}
function stageEvents(l,run){if(l.concept!=="input-int")return l.trace.map(summary=>({kind:"authored",summary}));if(!run)return authoredSession3Events();const vars=run.record?.vars||run.vars||{}, consumed=run.record?.inputs||run.inputs||[], inputs=consumed.map(x=>x.value);const canShow=run.record&&run.record.lessonId==="lesson03";if(!canShow)return [{kind:"authored",phase:"unavailable",summary:"Prepared visualization is not attached to this run. Use stdout/stderr for the edited program.",vars:{},inputs}];const hasPipeline=["avatar","rounds_text","rounds","tokens"].some(k=>vars[k]);if(!hasPipeline)return [{kind:"run-linked",phase:"output",summary:`This edited program does not match the token-counter trace. Actual stdout: ${JSON.stringify(run.stdout||"")}. No token pipeline state is shown.`,vars,inputs,stdout:run.stdout||""}];return [{kind:"run-linked",phase:"avatar",summary:consumed[0]?`Python input #1 supplied ${JSON.stringify(inputs[0]??"")}; avatar variable is ${valueLabel(vars.avatar)}`:vars.avatar?`avatar is ${valueLabel(vars.avatar)}, but this run consumed no input() for it. It may have been assigned directly in code.`:"avatar was not created in this run.",vars,inputs},{kind:"run-linked",phase:"rounds_text",summary:consumed[1]?`Python input #2 supplied ${JSON.stringify(inputs[1]??"")}; rounds_text is ${valueLabel(vars.rounds_text)}`:vars.rounds_text?`rounds_text is ${valueLabel(vars.rounds_text)}, but this run consumed no second input() for it. It may have been assigned directly in code.`:"No second input was consumed before the program stopped or finished.",vars,inputs},{kind:"run-linked",phase:"int",summary:vars.rounds?`Actual Python final state: rounds is ${valueLabel(vars.rounds)} while rounds_text is ${valueLabel(vars.rounds_text)}`:`rounds was not created; read the real error/output for why conversion stopped.`,vars,inputs},{kind:"run-linked",phase:"tokens",summary:vars.tokens?`Actual Python final state: tokens is ${valueLabel(vars.tokens)}`:`tokens was not created in this run.`,vars,inputs},{kind:"run-linked",phase:"output",summary:run.error?`Python ended with ${friendlyError(run.error)}`:"stdout shows the real prompt text and final message from Python.",vars,inputs,stdout:run.stdout||""}];}
function authoredSession3Events(){return [{kind:"authored",phase:"avatar",summary:'Authored demo: input #1 returns "Nori" for avatar',vars:{avatar:{value:"Nori",type:"str"},rounds_text:{value:"4",type:"str"},rounds:{value:4,type:"int"},tokens:{value:12,type:"int"}},inputs:["Nori","4"]},{kind:"authored",phase:"rounds_text",summary:'Authored demo: input #2 returns "4" for rounds_text',vars:{avatar:{value:"Nori",type:"str"},rounds_text:{value:"4",type:"str"},rounds:{value:4,type:"int"},tokens:{value:12,type:"int"}},inputs:["Nori","4"]},{kind:"authored",phase:"int",summary:'Authored demo: int("4") creates integer 4; rounds_text stays string "4"',vars:{avatar:{value:"Nori",type:"str"},rounds_text:{value:"4",type:"str"},rounds:{value:4,type:"int"},tokens:{value:12,type:"int"}},inputs:["Nori","4"]},{kind:"authored",phase:"tokens",summary:"Authored demo: 4 * 3 creates tokens = 12",vars:{avatar:{value:"Nori",type:"str"},rounds_text:{value:"4",type:"str"},rounds:{value:4,type:"int"},tokens:{value:12,type:"int"}},inputs:["Nori","4"]},{kind:"authored",phase:"output",summary:"Authored demo: Python prints Nori needs 12 tokens",vars:{avatar:{value:"Nori",type:"str"},rounds_text:{value:"4",type:"str"},rounds:{value:4,type:"int"},tokens:{value:12,type:"int"}},inputs:["Nori","4"]}];}
function valueLabel(v){return v?`${JSON.stringify(v.value)} (${v.type})`:"not created";}
function detectMultiplier(code){const m=code.match(/multiplier\s*=\s*(-?\d+)/);if(m)return Number(m[1]);const c=code.match(/correct\s*=\s*round_number\s*\*\s*(-?\d+)/);return c?Number(c[1]):2;}
function detectPoints(code){const m=code.match(/score\s*=\s*score\s*\+\s*(-?\d+)/);return m?Number(m[1]):1;}
function stageCells(l,ev,run){if(l.concept==="input-int"){const vars=ev.vars||{};return `<div class="slot ${["avatar","rounds_text"].includes(ev.phase)?"active":""}"><b>input text / str</b><br><span class="token">avatar = ${escapeHtml(valueLabel(vars.avatar))}</span><span class="token">rounds_text = ${escapeHtml(valueLabel(vars.rounds_text))}</span><p>empty string is supplied input; missing line is EOFError</p></div><div class="slot ${["int","tokens","output"].includes(ev.phase)?"active":""}"><b>actual Python state</b><br><span class="token">rounds = ${escapeHtml(valueLabel(vars.rounds))}</span><span class="token">tokens = ${escapeHtml(valueLabel(vars.tokens))}</span><span class="token">source: ${ev.kind==="run-linked"?"current run":"authored demo"}</span></div>`;}if(l.concept==="if-else")return `<div class="branch active"><b>comparison</b><br><span class="token">score >= threshold</span></div><div class="branch"><b>chosen branch</b><br>True path or False path, one output only</div>`;if(l.concept==="for-range"||l.concept==="integrated-game"||l.concept==="capstone")return `<div class="loop-cell active"><b>range strip</b><br><span class="token">1</span><span class="token">2</span><span class="token">3</span><span>stop not included</span></div><div class="slot"><b>score</b><br>${run?escapeHtml((run.stdout||"").split("\n").filter(x=>x.includes("Score")).slice(-1)[0]||"waiting"):"updates across rounds"}</div>`;if(l.concept==="function")return `<div class="function-frame active"><b>def</b><br>creates name, no body output yet</div><div class="function-frame"><b>call</b><br>argument becomes parameter</div>`;return `<div class="slot active"><b>current line</b><br><span class="token">${escapeHtml(ev.summary)}</span></div><div class="slot"><b>output / value</b><br>${run?escapeHtml((run.stdout||"").slice(0,80)):"appears only when Python prints"}</div>`;}
function stageStep(delta){const cur=Number($("#visualStage").dataset.step||0);renderStage(cur+delta,$("#visualStage")._lastRun||null);}
function playStage(){let i=0;const run=$("#visualStage")._lastRun||null;const max=stageEvents(currentLesson(),run).length;const tick=()=>{renderStage(i++,run);if(i<max&&!state.reduceMotion)setTimeout(tick,Number($("#speedSelect").value));};tick();}

function paintPortfolio(){const box=$("#portfolioList");if(!state.portfolio.length){box.innerHTML="<p>ยังไม่มีผลงานที่บันทึก / No saved artifacts yet.</p>";return;}box.innerHTML=state.portfolio.map(p=>{const code=p.evidence.sourceVersion?.code||p.evidence.code||"";const imported=p.evidence.trust==="imported";return `<article class="portfolio-card"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.product)} · ${escapeHtml(p.evidence.at)}</p><p>Status: ${imported?"Imported evidence pending local rerun":(p.evidence.lastChecks?.results?.every(r=>r.ok)?"Core behavior checks passed":"Evidence saved / review pending")}</p><code>${escapeHtml(code.slice(0,800))}</code></article>`;}).join("");}
function exportBackup(){downloadFile("prepython-backup.json",JSON.stringify(state,null,2),"application/json;charset=utf-8");}
function parentReport(){const lines=["Pre-Python Mini Game Studio parent summary","Runtime mode: Mode A real Python via Pyodide 0.26.4 when network/CDN is available.","No personal data is required. Work is local to this browser profile.",""];for(const l of lessons){const p=state.portfolio.find(x=>x.lessonId===l.id);lines.push(`${l.id}: ${textFor(l,"title")} - ${p?"evidence saved":"not yet saved"}`);if(p){lines.push(`Product: ${l.product}`);lines.push(`Reflection: ${p.evidence.reflection||"(empty)"}`);lines.push(`Checks: ${(p.evidence.lastChecks?.results||[]).map(r=>`${r.name}:${r.ok?"pass":"try again"}`).join(", ")}`);}}downloadFile("parent-report.txt",lines.join("\n"),"text/plain;charset=utf-8");}
function finalPackage(){const l=lessons[7], ls=lessonState(l.id);const code=ls.evidence?.sourceVersion?.code || ls.code || l.starter;downloadFile("my_arcade_package.txt",`How to play: run my_arcade.py in Python 3 and answer three multiplication questions.\nUse fictional names only.\n\n--- my_arcade.py ---\n${code}\n\n--- test log ---\n${JSON.stringify(ls.evidence?.lastChecks||{},null,2)}`,"text/plain;charset=utf-8");}
function readImport(e){const file=e.target.files[0];if(!file||file.size>2_000_000)return alert("Unsupported or too large.");const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(data.schema!==1||!data.curriculum)throw new Error("Unsupported schema");importPayload=data;$("#importPreview").textContent=`Workspace ${data.workspaceId}\nLessons: ${Object.keys(data.lessons||{}).length}\nPortfolio: ${(data.portfolio||[]).length}`;$("#importDialog").showModal();}catch(err){alert("Invalid backup: "+err.message);}};r.readAsText(file);}
function confirmImport(){const clean=sanitizeImport(importPayload);Object.assign(state,clean);$("#importDialog").close();paintI18n();paintHome();paintLesson();saveState("Imported; evidence pending rerun");}
function sanitizeImport(data){const fresh=blankState();fresh.workspaceId=data.workspaceId||fresh.workspaceId;fresh.lang=data.lang==="en"?"en":"th";fresh.mode="practice";fresh.currentLesson=Number.isInteger(data.currentLesson)?Math.max(0,Math.min(7,data.currentLesson)):0;for(const [id,raw] of Object.entries(data.lessons||{})){if(!lessons.some(l=>l.id===id))continue;const ls=lessonState(id);fresh.lessons[id]={...ls,...raw,testsStale:true,review:null};if(fresh.lessons[id].evidence){fresh.lessons[id].evidence={...fresh.lessons[id].evidence,trust:"imported",reviewPending:true,lastChecks:null,lastRun:null};}}fresh.portfolio=(data.portfolio||[]).filter(p=>lessons.some(l=>l.id===p.lessonId)).slice(0,8).map(p=>({...p,evidence:{...(p.evidence||{}),trust:"imported",reviewPending:true,lastChecks:null,lastRun:null}}));return fresh;}
function clearData(){if(confirm("Export a backup first. Clear all local learning work on this browser profile?")){localStorage.removeItem(STORE_KEY);location.reload();}}
function downloadFile(name,content,type){const blob=new Blob([content],{type});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},0);}
function toggleTimer(){if(timerId){clearInterval(timerId);timerId=0;return;}timerId=setInterval(()=>{timerLeft=Math.max(0,timerLeft-1);paintTimer();if(!timerLeft)clearInterval(timerId);},1000);}
function paintTimer(){const m=String(Math.floor(timerLeft/60)).padStart(2,"0"),s=String(timerLeft%60).padStart(2,"0");$("#timerReadout").textContent=`${m}:${s}`;}
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
function escapeHtml(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));}
function escapeReg(s){return s.replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
function normalizeOut(s){return String(s).replace(/\r\n/g,"\n");}
document.addEventListener("DOMContentLoaded",init);
