window.PP_LESSONS = [
{id:"lesson01",py:"lesson01_sign.py",titleTh:"เปิดป้ายเกมของฉัน",titleEn:"Open My Arcade Sign",concept:"sequence-print",product:"หน้าต้อนรับเกม",objectiveTh:"ใช้ print สร้างข้อความอย่างน้อย 4 บรรทัดตามลำดับที่ตั้งใจ",objectiveEn:"Use print to create at least four messages in the intended order.",starter:'print("NEON HOP")\nprint("Get ready")\nprint("Go!")\n',inputs:"",challengeTh:"สร้าง 4 บรรทัด: ชื่อเกม กติกา 1 ข้อ ข้อความเตรียมตัว และข้อความเริ่ม",challengeEn:"Create four lines: title, one rule, ready message, and start message.",agenda:[["mission launch and prerequisite check",7],["predict and explore the visual lab",10],["teacher worked example and think-aloud",13],["learner types/copies, runs, and traces the example",13],["screen/standing break",5],["guided modification with a thinking partner",15],["individual performance challenge",15],["test, explain, and save evidence",8],["exit check and next-session link",4]],criteria:["มี output 4 บรรทัดตามลำดับ","บันทึกคำคาดเดาก่อนรัน","แก้ตัวอย่าง print(\"Ready) ให้รันได้"],hints:["บรรทัดบนทำก่อนบรรทัดล่าง","ข้อความต้องอยู่ในเครื่องหมายคำพูดครบคู่","ตัวอย่าง: print(\"Start!\")"],misconception:"print แสดงข้อความ ไม่ได้ทำให้ตัวละครกระโดดหรือรอ",exit:"ถ้า Go! เป็นบรรทัดแรก จะเกิดอะไรขึ้น?",tests:[{name:"four output lines",inputs:[],kind:"stdoutMinLines",min:4},{name:"uses print",kind:"ast",node:"Call",func:"print"}],trace:["คำสั่งแรกเพิ่มข้อความในริบบอน output","คำสั่งถัดไปเพิ่มข้อความต่อท้าย ไม่แทนที่ของเดิม","ลำดับบรรทัดคือสิ่งที่กำหนดลำดับ output"]},
{id:"lesson02",py:"lesson02_score.py",titleTh:"แผงคะแนนที่จำค่าได้",titleEn:"Make a Score That Remembers",concept:"variables",product:"กระดานคะแนน",objectiveTh:"ติดตามค่าคะแนนก่อนและหลัง assignment และการคำนวณ",objectiveEn:"Trace score values before and after assignment and arithmetic.",starter:'game_name = "NEON HOP"\nscore = 0\nscore = score + 10\nprint(game_name)\nprint("Score:", score)\n',inputs:"",challengeTh:"เริ่มที่ 2 เพิ่ม 4 ลด 1 แล้วพิมพ์คะแนนสุดท้าย ต้องได้ 5",challengeEn:"Start at 2, gain 4, lose 1, then print the final score: 5.",agenda:null,criteria:["ผลสุดท้ายเป็น Score: 5","อธิบาย 2 → 6 → 5 ได้","ทดสอบ variation 10 + 3 - 2 = 11"],hints:["ด้านขวาของ = อ่านค่าปัจจุบันก่อน","score = score + 4 หมายถึงใช้ค่าเก่าแล้วเก็บค่าใหม่","ระวัง score กับ Score เป็นคนละชื่อ"],misconception:"= ใน Python คือ assignment ไม่ใช่เครื่องหมายเท่ากันทางคณิตศาสตร์",exit:"หลัง score = 4 แล้ว score = score + 3 ค่าปัจจุบันคืออะไร?",tests:[{name:"timeline 2 to 6 to 5",inputs:[],exactStdout:"NEON HOP\nScore: 5\n"},{name:"has assignment",kind:"ast",node:"Assign"}],trace:["สร้างชื่อ game_name ให้ชี้ไปที่ข้อความ","score เริ่มที่ 0","อ่าน score เก่า บวก 10 แล้วเก็บค่ากลับไปที่ score"]},
{id:"lesson03",py:"lesson03_tokens.py",titleTh:"เคาน์เตอร์โทเคนที่รับข้อมูลได้",titleEn:"Build a Token Counter",concept:"input-int",product:"เคาน์เตอร์โทเคน",objectiveTh:"ใช้ input สองค่า แปลงข้อความตัวเลขด้วย int แล้วคำนวณโทเคน",objectiveEn:"Use two inputs, convert numeric text with int, and calculate tokens.",starter:'avatar = input("Fictional avatar: ")\nrounds_text = input("Rounds (1-5): ")\nrounds = int(rounds_text)\ntokens = rounds * 3\nprint(avatar, "needs", tokens, "tokens")\n',inputs:"Nori\n4",challengeTh:"เปลี่ยนเป็น 4 โทเคนต่อรอบ แล้วทดสอบ Nori/1 และ Pip/5",challengeEn:"Change to four tokens per round, then test Nori/1 and Pip/5.",agenda:null,criteria:["Nori, 1 → Nori needs 4 tokens","Pip, 5 → Pip needs 20 tokens","อธิบาย rounds_text เป็น str และ rounds เป็น int","Nori, cat ต้องเกิด ValueError จริง"],hints:["input() ให้ข้อความเสมอ แม้พิมพ์เลข","int(rounds_text) สร้างเลขจำนวนเต็มจากข้อความที่เหมาะสม","ถ้าใส่ cat ใน int จะเกิด ValueError"],misconception:"ข้อความ \"4\" กับเลข 4 ไม่ใช่ชนิดเดียวกัน",exit:"หลังแปลงแล้ว rounds_text และ rounds มีค่า/ชนิดต่างกันอย่างไร?",tests:[{name:"Nori one round four tokens",inputs:["Nori","1"],exactStdout:"Fictional avatar: Rounds (1-5): Nori needs 4 tokens\n"},{name:"Pip five rounds four tokens",inputs:["Pip","5"],exactStdout:"Fictional avatar: Rounds (1-5): Pip needs 20 tokens\n"},{name:"Zed two rounds counterexample",inputs:["Zed","2"],exactStdout:"Fictional avatar: Rounds (1-5): Zed needs 8 tokens\n"},{name:"invalid numeric text",inputs:["Nori","cat"],expectError:"ValueError"},{name:"uses int",kind:"ast",node:"Call",func:"int"},{name:"uses multiplication",kind:"ast",node:"BinOp"}],trace:["input แรกเก็บข้อความ avatar","input ที่สองเก็บข้อความ rounds_text เช่น \"4\"","int สร้างค่า integer 4 ใน rounds","คูณ rounds ด้วยราคาต่อรอบแล้ว print ผล"]},
{id:"lesson04",py:"lesson04_gate.py",titleTh:"ประตูโบนัสที่มีกติกา",titleEn:"Open a Rule Based Bonus Gate",concept:"if-else",product:"ประตูโบนัส",objectiveTh:"ใช้ if/else เลือกทางตามคะแนนและอธิบายกรณีเท่ากับเกณฑ์",objectiveEn:"Use if/else to choose a path and explain the boundary case.",starter:'score_text = input("Score: ")\nscore = int(score_text)\nif score >= 10:\n    print("BONUS OPEN")\nelse:\n    print("PRACTICE READY")\n',inputs:"10",challengeTh:"สร้างประตู threshold >= 8 และ variation == 8 พร้อมทดสอบ 7/8/9",challengeEn:"Create a >= 8 gate and an == 8 variation; test 7/8/9.",agenda:null,criteria:[">= 8: 7 ปิด, 8 เปิด, 9 เปิด","== 8: 7 ปิด, 8 เปิด, 9 ปิด","จับบั๊ก > กับ >= ด้วย input 8"],hints:["เครื่องหมาย : เปิดบล็อก","บรรทัดใน if/else ต้องเยื้อง 4 ช่อง","== ใช้เปรียบเทียบ ส่วน = ใช้เก็บค่า"],misconception:"else ทำงานเมื่อเงื่อนไข if เป็น False",exit:"input ใดแยกความต่างระหว่าง >= 8 กับ > 8?",tests:[{name:">=8 below",inputs:["7"],exactStdout:"Score: PRACTICE READY\n"},{name:">=8 equal",inputs:["8"],exactStdout:"Score: BONUS OPEN\n"},{name:">=8 above",inputs:["9"],exactStdout:"Score: BONUS OPEN\n"},{name:"has if",kind:"ast",node:"If"}],trace:["แปลงคะแนนเป็น integer","ประเมิน comparison เป็น True หรือ False","เปิดเฉพาะ branch ที่ถูกเลือก"]},
{id:"lesson05",py:"lesson05_rounds.py",titleTh:"เกมซ้อมสามรอบ",titleEn:"Build a Three Round Practice Machine",concept:"for-range",product:"เครื่องฝึกหลายรอบ",objectiveTh:"ใช้ for/range เล่นซ้ำตามจำนวนรอบและสะสมคะแนน",objectiveEn:"Use for/range to repeat and accumulate score.",starter:'score = 0\nfor round_number in range(1, 4):\n    score = score + 2\n    print("Round", round_number, "Score", score)\nprint("Final", score)\n',inputs:"",challengeTh:"สร้าง 5 รอบ รอบละ 2 คะแนน Final ต้องพิมพ์ครั้งเดียวและได้ 10",challengeEn:"Create five rounds at two points each; Final prints once and is 10.",agenda:null,criteria:["มี Round 1 ถึง Round 5","Final 10 ปรากฏครั้งเดียว","อธิบาย stop ใน range ไม่ถูกรวม"],hints:["range(1, 6) ให้ 1,2,3,4,5","บรรทัดที่เยื้องอยู่ใน loop","Final ไม่ควรเยื้องถ้าต้องการพิมพ์ครั้งเดียว"],misconception:"stop ของ range ไม่รวมอยู่ในค่าที่วน",exit:"range(1, 6) ให้ค่าอะไรบ้าง และ Final ควรเยื้องไหม?",tests:[{name:"five rounds exact",inputs:[],exactStdout:"Round 1 Score 2\nRound 2 Score 4\nRound 3 Score 6\nRound 4 Score 8\nRound 5 Score 10\nFinal 10\n"},{name:"final once",kind:"count",text:"Final",count:1},{name:"has for",kind:"ast",node:"For"}],trace:["score เริ่ม 0","round_number รับค่า 1,2,3 ตาม range","score สะสมเพิ่มในแต่ละรอบ","Final อยู่ข้างนอก loop จึงพิมพ์ครั้งเดียว"]},
{id:"lesson06",py:"lesson06_tool.py",titleTh:"เครื่องมือแสดงคะแนนของฉัน",titleEn:"Make a Reusable Score Tool",concept:"function",product:"เครื่องมือเรียกใช้ซ้ำ",objectiveTh:"แยก def ออกจาก call และส่ง argument เข้า parameter หนึ่งตัว",objectiveEn:"Separate definition from calls and pass one argument into one parameter.",starter:'def show_score(points):\n    print("Score:", points)\n\nshow_score(2)\nshow_score(5)\n',inputs:"",challengeTh:"สร้าง announce_round(number) แล้วเรียกสำหรับ 1, 2, 3",challengeEn:"Create announce_round(number), then call it for 1, 2, and 3.",agenda:null,criteria:["Round 1, Round 2, Round 3 ปรากฏ","def อย่างเดียวไม่พิมพ์ body","argument ต่างกันให้ output ต่างกัน"],hints:["def สร้างเครื่องมือ แต่ยังไม่ใช้งาน body","ต้องมีวงเล็บเพื่อ call เช่น show_score(5)","parameter คือชื่อรับค่าข้างใน function"],misconception:"print ไม่ใช่ return และ def ไม่ได้พิมพ์เองจนกว่าจะ call",exit:"ถ้า define function แต่ไม่ call จะเห็นอะไร?",tests:[{name:"three announce_round calls exact",inputs:[],exactStdout:"Round 1\nRound 2\nRound 3\n"},{name:"has function",kind:"ast",node:"FunctionDef"},{name:"calls announce_round",kind:"ast",node:"Call",callName:"announce_round"}],trace:["def ลงทะเบียนชื่อ function โดยยังไม่พิมพ์ body","call show_score(2) สร้าง frame points = 2","call ครั้งต่อไปใช้ body เดิมกับค่าใหม่"]},
{id:"lesson07",py:"lesson07_game.py",titleTh:"ประกอบเกม Double Dash",titleEn:"Assemble Double Dash",concept:"integrated-game",product:"Math Arcade 3 รอบ",objectiveTh:"รวม input/int/if/for/function เป็นเกมสามรอบแบบ deterministic",objectiveEn:"Combine input/int/if/for/function into a deterministic three-round game.",starter:'def show_score(points):\n    print("Score:", points)\n\nscore = 0\nfor round_number in range(1, 4):\n    print("Round", round_number)\n    answer_text = input("Round number x 2 = ")\n    answer = int(answer_text)\n    correct = round_number * 2\n    if answer == correct:\n        score = score + 1\n        print("Hit!")\n    else:\n        print("Try again next round")\n    show_score(score)\nprint("Game over")\n',inputs:"2\n0\n6",challengeTh:"เปลี่ยนคะแนนต่อข้อถูกจาก 1 เป็น 2 แล้วทดสอบ all-correct/all-wrong/mixed",challengeEn:"Change points per correct answer from 1 to 2 and test all-correct/all-wrong/mixed.",agenda:[["retrieve prior building blocks",7],["predict scores from input queues",10],["teacher assembles and traces one round",13],["partners run the starter",13],["break",5],["remix points and messages",15],["individual debugging and three-case testing",15],["explain one wrong-answer round and save evidence",8],["plan one change for the final studio",4]],criteria:["หลังเปลี่ยนเป็นสองคะแนน: 2,4,6 → final score 6","0,0,0 → final score 0","2,0,6 → final score 4"],hints:["score ต้องอยู่ก่อน loop เพื่อสะสมข้ามรอบ","if อยู่ใน loop แต่ไม่ใช่ nested loop","show_score(score) ใช้ค่าปัจจุบันของ score"],misconception:"score = 0 อยู่ใน loop จะล้างคะแนนทุกรอบ",exit:"ถ้า score = 0 ถูกย้ายเข้า for จะเสียอะไร?",tests:[{name:"all correct after two-point remix",kind:"dynamicScore",pattern:"correct",requirePoints:2},{name:"all wrong after two-point remix",kind:"dynamicScore",pattern:"wrong",requirePoints:2},{name:"mixed after two-point remix",kind:"dynamicScore",pattern:"mixed",requirePoints:2},{name:"has loop",kind:"ast",node:"For"},{name:"has branch",kind:"ast",node:"If"}],trace:["แต่ละรอบรับคำตอบหนึ่งค่า","correct คำนวณจาก round_number","branch ถูก/ผิดตัดสินว่าจะเพิ่ม score หรือไม่","show_score แสดงคะแนนหลังรอบนั้น"]},
{id:"lesson08",py:"my_arcade.py",titleTh:"เปิดอาร์เคดเกมแรกของฉัน",titleEn:"Open My First Arcade",concept:"capstone",product:"เกมฉบับของฉัน",objectiveTh:"ปรับกติกา ทดสอบสามรูปแบบ อธิบายหนึ่งบรรทัดและหนึ่งการแก้บั๊ก",objectiveEn:"Customize the rule, test three patterns, and explain one line plus one fix.",starter:'def show_score(points):\n    print("Score:", points)\n\ngame_name = "BEAT BOOST"\navatar = input("Fictional avatar: ")\nmultiplier = 3\nscore = 0\nprint(game_name)\nprint("Multiply each round number by", multiplier)\nfor round_number in range(1, 4):\n    print("Round", round_number)\n    answer_text = input("Your answer: ")\n    answer = int(answer_text)\n    correct = round_number * multiplier\n    if answer == correct:\n        score = score + 1\n        print("Hit!")\n    else:\n        print("Try again next round")\n    show_score(score)\nprint("Thanks", avatar)\n',inputs:"Nori\n3\n0\n9",challengeTh:"เลือก multiplier 2–4 หรือคะแนน 1–3 แล้วสร้าง my_arcade.py พร้อมผลทดสอบสามชุด",challengeEn:"Choose multiplier 2-4 or points 1-3 and build my_arcade.py with three test records.",agenda:[["review the current game and select a goal",8],["plan a change and predict its effect",10],["teacher models requirements/testing on a different example",12],["build",13],["break",5],["build and short teacher check-ins",20],["run three test patterns and fix a bug",12],["paired showcase and brief explanation",7],["export and reflection",3]],criteria:["มีชื่อเกม fiction และ avatar fiction","มี 3 รอบ if/else score และ function call","ทดสอบ all-correct/all-wrong/mixed ตามกติกาที่เลือก","มีบันทึกก่อน/หลังแก้บั๊ก"],hints:["เปลี่ยน multiplier หรือคะแนนต่อข้อถูกพอแล้ว","หลังเปลี่ยนกติกา ต้องเปลี่ยน expected tests ด้วย","ใช้ข้อมูล fiction ไม่ใช้ชื่อจริง"],misconception:"สีหรือธีมเป็นการตกแต่ง แต่พฤติกรรม Python ต้องเปลี่ยนจริง",exit:"บรรทัดไหนแสดงกติกาที่เปลี่ยน และ test ไหนพิสูจน์?",tests:[{name:"custom all correct",kind:"dynamicScore",pattern:"correct",withAvatar:true,avatar:"Nori"},{name:"custom all wrong",kind:"dynamicScore",pattern:"wrong",withAvatar:true,avatar:"Nori"},{name:"custom mixed",kind:"dynamicScore",pattern:"mixed",withAvatar:true,avatar:"Nori"},{name:"has function",kind:"ast",node:"FunctionDef"},{name:"has loop",kind:"ast",node:"For"},{name:"has branch",kind:"ast",node:"If"}],trace:["เกมรับ avatar fiction ก่อน","แต่ละรอบใช้ multiplier คำนวณคำตอบที่ถูก","ถ้าตอบถูก score เพิ่ม ถ้าผิด score คงเดิม","ท้ายเกมขอบคุณ avatar fiction"]}
];

for (const lesson of window.PP_LESSONS) {
  if (!lesson.agenda) lesson.agenda = [
    ["mission launch and prerequisite check",7],["predict and explore the visual lab",10],["teacher worked example and think-aloud",13],
    ["learner types/copies, runs, and traces the example",13],["screen/standing break",5],["guided modification with a thinking partner",15],
    ["individual performance challenge",15],["test, explain, and save evidence",8],["exit check and next-session link",4]
  ];
}

window.PP_I18N = {
  th:{appTitle:"Pre-Python Mini Game Studio",mode:"โหมด",practiceMode:"ฝึกเอง",teacherMode:"ครูฉายหน้าห้อง",portfolioMode:"แฟ้มผลงาน",reduceMotion:"ลดการเคลื่อนไหว",courseMeta:"อายุ 10+ · 8 ครั้ง · ครั้งละ 90 นาที · รวม 12 ชั่วโมง",courseTitleTh:"ค่อย ๆ สร้างเกมข้อความด้วย Python จริง",coursePromise:"ผู้เรียนจะอ่าน พิมพ์ แก้ ทดสอบ และอธิบายโปรแกรม Python ขนาดเล็กที่ใช้ output, ตัวแปร, input, int, if/else, for/range และฟังก์ชันหนึ่งพารามิเตอร์",startSession:"เริ่มครั้งที่ 1",continueWork:"ทำงานต่อ",exportBackup:"ส่งออกข้อมูล",importBackup:"นำเข้าข้อมูล",visualStage:"เวทีอธิบายโค้ด",play:"เล่น",codeWorkbench:"โต๊ะเขียนโค้ด",copy:"คัดลอก",downloadPy:"ดาวน์โหลด .py",resetCode:"คืนโค้ดเริ่มต้น",inputsForRun:"Inputs for this run: ใส่หนึ่งบรรทัดต่อ input() · ใช้ <empty> สำหรับข้อความว่าง",runPython:"Run Python",stop:"Stop",check:"Check",inputTranscript:"บันทึก input ที่ถูกใช้",prediction:"คาดเดาก่อนรัน",reflection:"อธิบายสิ่งที่เห็น",hints:"ตัวช่วยแบบค่อยเป็นค่อยไป",nextHint:"ขอตัวช่วยถัดไป",missionCard:"ภารกิจและหลักฐาน",rubric:"รูบริก 0–2",teacherReason:"บันทึกครู / เหตุผล",saveEvidence:"บันทึกหลักฐาน",teacherReviewed:"ครูบันทึกว่าแสดงความเข้าใจแล้ว",misconception:"จุดที่มักเข้าใจผิด:",exitCheck:"Exit check:",parentReport:"รายงานผู้ปกครอง",finalPackage:"แพ็กเกจเกมสุดท้าย",clearData:"ล้างข้อมูลเครื่องนี้",importPreview:"ตรวจข้อมูลก่อนนำเข้า",confirm:"ยืนยัน",cancel:"ยกเลิก",lineExplain:"อธิบายทีละบรรทัด",activityPath:"เส้นทางกิจกรรม",supportStretch:"ตัวช่วยและต่อยอด",debugLab:"ห้องแก้บั๊ก"},
  en:{appTitle:"Pre-Python Mini Game Studio",mode:"Mode",practiceMode:"Practice",teacherMode:"Teacher",portfolioMode:"Portfolio",reduceMotion:"Reduce motion",courseMeta:"Age 10+ · 8 sessions · 90 minutes each · 12 hours total",courseTitleTh:"Build a real Python text game step by step",coursePromise:"Learners read, type, change, test, and explain small Python programs using output, variables, input, int, if/else, for/range, and one-parameter functions.",startSession:"Start Session 1",continueWork:"Continue my work",exportBackup:"Export backup",importBackup:"Import backup",visualStage:"Teaching stage",play:"Play",codeWorkbench:"Code workbench",copy:"Copy",downloadPy:"Download .py",resetCode:"Reset starter",inputsForRun:"Inputs for this run: one line per input(); use <empty> for an empty string",runPython:"Run Python",stop:"Stop",check:"Check",inputTranscript:"Consumed input transcript",prediction:"Prediction before run",reflection:"Explain what happened",hints:"Graduated hints",nextHint:"Next hint",missionCard:"Mission and evidence",rubric:"Rubric 0-2",teacherReason:"Teacher note / reason",saveEvidence:"Save evidence",teacherReviewed:"Teacher reviewed as demonstrated",misconception:"Common misconception:",exitCheck:"Exit check:",parentReport:"Parent report",finalPackage:"Final package",clearData:"Clear this device",importPreview:"Preview import",confirm:"Confirm",cancel:"Cancel",lineExplain:"Line-by-line explanation",activityPath:"Activity path",supportStretch:"Support and stretch",debugLab:"Debug lab"}
};

Object.assign(window.PP_LESSONS.find(l => l.id === "lesson03"), {
  lineExplanations: [
    {line:1, th:"input แรกแสดง prompt แล้วรับข้อความสำหรับ avatar แบบ fiction เท่านั้น", en:"The first input shows a prompt and receives fictional avatar text."},
    {line:2, th:"input ที่สองรับจำนวนรอบเป็นข้อความ จึงเก็บไว้ใน rounds_text", en:"The second input receives the round count as text and stores it in rounds_text."},
    {line:3, th:"int(rounds_text) พยายามสร้างจำนวนเต็ม ถ้าข้อความไม่ใช่เลขจะเกิด ValueError จริง", en:"int(rounds_text) tries to create an integer; nonnumeric text raises a real ValueError."},
    {line:4, th:"tokens ใช้เลข rounds คูณราคาต่อรอบ ในภารกิจอิสระต้องเปลี่ยนราคาเป็น 4", en:"tokens uses the integer rounds times the per-round price. The independent task changes the price to 4."},
    {line:5, th:"print รวมข้อความ avatar ค่า tokens และคำว่า tokens ลง stdout", en:"print writes avatar text, the token value, and the word tokens to stdout."}
  ],
  activityPath: [
    {phase:"worked", th:"Start together: รันตัวอย่าง Nori / 4 แล้วชี้ว่า \"4\" เป็น str ก่อนแปลง", en:"Start together: run Nori / 4 and point out that \"4\" is a str before conversion."},
    {phase:"guided", th:"Make it yours together: เปลี่ยนราคาจาก 3 เป็น 2 แล้วทำนาย Nori / 4 = 8", en:"Guided change: change price from 3 to 2 and predict Nori / 4 = 8."},
    {phase:"independent", th:"Independent: เปลี่ยนเป็น 4 โทเคนต่อรอบ ทดสอบ Nori / 1 และ Pip / 5 แล้วบันทึกหลักฐาน", en:"Independent: change to four tokens per round, test Nori / 1 and Pip / 5, then save evidence."},
    {phase:"assessment", th:"Assessment: อธิบายว่า rounds_text ยังเป็น str แต่ rounds เป็น int และทดลอง Nori / cat เพื่ออ่าน ValueError", en:"Assessment: explain that rounds_text remains str while rounds is int, then try Nori / cat to interpret ValueError."}
  ],
  scaffold: {
    th:["ใช้ input queue สองบรรทัดเสมอ: avatar แล้ว rounds","วงกลมคำว่า int(...) ก่อนรัน เพื่อจำว่าบรรทัดนี้เป็นจุดแปลงชนิด","ถ้าติด ให้เริ่มจากแก้เฉพาะเลข 3 เป็น 4"],
    en:["Always use two input queue lines: avatar, then rounds","Circle int(...) before running; this is the conversion point","If stuck, start by changing only 3 to 4"]
  },
  stretch: {
    th:"เลือก token price เล็ก ๆ อีกหนึ่งค่า เช่น 2 หรือ 5 แล้วทำนายสองกรณีก่อนรัน โดยไม่เพิ่ม syntax ใหม่",
    en:"Choose one more small token price, such as 2 or 5, and predict two cases before running without adding new syntax."
  },
  debugTask: {
    code:'avatar = input("Fictional avatar: ")\nrounds_text = input("Rounds (1-5): ")\nrounds = int(rounds_text)\ntokens = rounds_text * 4\nprint(avatar, "needs", tokens, "tokens")',
    promptTh:"บั๊กนี้ยังรันได้แต่ผลผิดเมื่อใส่ 4: ได้ 4444 เพราะใช้ rounds_text ที่เป็น str แทน rounds ที่เป็น int ให้แก้บรรทัด tokens",
    promptEn:"This bug still runs but gives 4444 for input 4 because it uses rounds_text (str) instead of rounds (int). Fix the tokens line."
  },
  rubricAnchors: {
    behavior:"2 = Nori/1 gives 4, Pip/5 gives 20, and invalid numeric text raises ValueError rather than passing.",
    change:"2 = price changed intentionally to 4 with a correct prediction for at least one new input.",
    explain:"2 = explains that input returns str, int creates an integer, and rounds_text remains unchanged.",
    debug:"2 = uses Nori/cat or the rounds_text * 4 bug to explain and verify the fix."
  }
});


Object.assign(window.PP_LESSONS.find(l => l.id === "lesson06"), {
  bridgeCode:'def show_score(points):\n    print("Score:", points)\n\nscore = 3\nshow_score(score)\nscore = score + 2\nshow_score(score)\n',
  bridgeTests:[
    {name:"variable-argument bridge exact",inputs:[],exactStdout:"Score: 3\nScore: 5\n"},
    {name:"bridge uses show_score calls",kind:"ast",node:"Call",callName:"show_score"}
  ],
  activityPath:[
    {phase:"worked",th:"รัน show_score(2) และ show_score(5) เพื่อเห็นว่า argument ต่างกันใช้ body เดิม",en:"Run show_score(2) and show_score(5) to see different arguments use the same body."},
    {phase:"guided",th:"เปลี่ยน label ใน function หนึ่งครั้ง แล้วดูว่าทั้งสอง call เปลี่ยนตาม",en:"Change the label inside the function once and see both calls change."},
    {phase:"bridge",th:"รัน bridge: score = 3, show_score(score), เพิ่มเป็น 5, show_score(score) ต้องได้ Score: 3 และ Score: 5",en:"Run the bridge: score = 3, show_score(score), update to 5, show_score(score); expect Score: 3 and Score: 5."},
    {phase:"independent",th:"สร้าง announce_round(number) แล้ว call สำหรับ 1, 2, 3",en:"Create announce_round(number) and call it for 1, 2, 3."}
  ],
  lineExplanations:[
    {line:1,th:"def ตั้งชื่อเครื่องมือและ parameter points",en:"def names the tool and parameter points."},
    {line:2,th:"body จะทำงานเฉพาะตอนถูก call",en:"The body runs only when called."},
    {line:4,th:"argument 2 ถูกส่งเข้า points",en:"Argument 2 is passed into points."},
    {line:5,th:"argument 5 ใช้ body เดิมอีกครั้ง",en:"Argument 5 reuses the same body."}
  ],
  scaffold:{th:["ดูว่า def ไม่พิมพ์เอง","call ต้องมีวงเล็บ","ใช้ตัวแปร score เป็น argument ได้"],en:["Notice def does not print by itself","A call needs parentheses","A variable such as score can be an argument"]},
  stretch:{th:"ใช้ตัวแปรเป็น argument ใน announce_round โดยไม่เพิ่ม return",en:"Use a variable as the argument in announce_round without adding return."},
  debugTask:{code:'def show_score(points):\n    print("Score:", points)\n\nshow_score',promptTh:"บรรทัดสุดท้ายยังไม่ call เพราะไม่มีวงเล็บ ให้แก้เป็น show_score(5)",promptEn:"The last line is not a call because it has no parentheses. Fix it to show_score(5)."},
  rubricAnchors:{behavior:"2 = function definition plus real calls produce required distinct outputs.",change:"2 = changes label or argument intentionally and predicts effect.",explain:"2 = separates defining from calling and traces argument to parameter.",debug:"2 = fixes missing call/bare name and verifies output."}
});

const EXPLICIT_LESSON_PATCHES = {
lesson01:{lineExplanations:[{line:1,th:"print แรกสร้าง output บรรทัดแรก: ชื่อป้ายเกม",en:"First print creates the first output line: the sign title."},{line:2,th:"print ถัดไปเพิ่มข้อความต่อท้ายตามลำดับ",en:"Next print appends text in order."},{line:3,th:"Python ทำงานบนลงล่าง Go! จึงออกท้ายสุดในตัวอย่าง",en:"Python runs top to bottom, so Go! appears last in the example."}],activityPath:[{phase:"worked",th:"รัน NEON HOP / Get ready / Go! แล้วชี้ output ทีละบรรทัด",en:"Run NEON HOP / Get ready / Go! and point at each output line."},{phase:"guided",th:"เปลี่ยนชื่อเกมและสลับสองบรรทัด ทำนายก่อนรัน",en:"Change the game title and swap two lines; predict before running."},{phase:"independent",th:"สร้าง 4 print lines: title, rule, ready, start",en:"Create four print lines: title, rule, ready, start."},{phase:"debug",th:"ซ่อม print(\"Ready) โดยเติม quote ที่หายไป",en:"Repair print(\"Ready) by adding the missing quote."}],scaffold:{th:["ใช้ symbol helper สำหรับ quote และวงเล็บ","เริ่มจาก 2 บรรทัดแล้วเพิ่มเป็น 4","ใช้ Move up/Move down แทนการลาก"],en:["Use the symbol helper for quotes and parentheses","Start with two lines, then add to four","Use Move up/Move down instead of dragging"]},stretch:{th:"สร้างสองลำดับ output แล้วอธิบายว่าลำดับไหนช่วยผู้เล่นกว่า",en:"Create two output orders and explain which helps the player more."},debugTask:{code:'print(\"Ready)\nprint(\"Go!\")',promptTh:"quote หลัง Ready หายไป ทำให้ SyntaxError ต้องเติม quote แล้วรันใหม่",promptEn:"The quote after Ready is missing, causing SyntaxError. Add it and rerun."},rubricAnchors:{behavior:"2 = four output lines appear once in intended order.",change:"2 = title/order changed deliberately with prediction.",explain:"2 = identifies first/last line and execution order.",debug:"2 = repairs missing quote and verifies output."}},
lesson02:{lineExplanations:[{line:1,th:"game_name เป็นชื่อที่ชี้ไปยังข้อความ",en:"game_name is a name referring to text."},{line:2,th:"score เก็บ integer ปัจจุบัน",en:"score stores the current integer."},{line:3,th:"ด้านขวาอ่านค่าเก่า คำนวณ แล้ว assignment เก็บค่าใหม่",en:"The right side reads the old value, calculates, then assignment stores the new value."},{line:5,th:"print แสดงค่าปัจจุบัน ไม่ใช่ค่าทุกค่าในอดีต",en:"print shows the current value, not every old value."}],activityPath:[{phase:"worked",th:"trace 0 → 10",en:"Trace 0 to 10."},{phase:"guided",th:"เปลี่ยนเริ่ม 5 เพิ่ม 3 คาดเดา 8",en:"Change start to 5, gain 3, predict 8."},{phase:"independent",th:"เริ่ม 2 เพิ่ม 4 ลด 1 ต้องได้ 5",en:"Start 2, gain 4, lose 1; final must be 5."},{phase:"debug",th:"แก้ Score/score NameError",en:"Fix Score/score NameError."}],scaffold:{th:["เติม score timeline ก่อนรัน","พูด Before this line / after this line","จำว่า score และ Score ไม่ใช่ชื่อเดียวกัน"],en:["Fill the score timeline before running","Say before this line / after this line","Remember score and Score are different names"]},stretch:{th:"ทำนาย subtraction หรือ multiplication ด้วยเลขเล็กแล้วตรวจ",en:"Predict a subtraction or multiplication with small numbers, then check."},debugTask:{code:'score = 2\nscore = score + 4\nprint(\"Score:\", Score)',promptTh:"Score ตัวใหญ่ยังไม่มีค่า ให้แก้เป็น score",promptEn:"Uppercase Score has no value; fix it to score."},rubricAnchors:{behavior:"2 = correct final value and second variation.",change:"2 = starting value/rule changed intentionally.",explain:"2 = explains right side before assignment update.",debug:"2 = finds case-sensitive name mismatch."}},
lesson04:{lineExplanations:[{line:1,th:"input รับ score เป็น str",en:"input receives score as str."},{line:2,th:"int แปลง score_text เป็น int",en:"int converts score_text to int."},{line:3,th:"if score >= 8 เลือกจาก True/False",en:"if score >= 8 chooses from True/False."},{line:4,th:"บล็อกเยื้องทำงานเมื่อ True",en:"Indented block runs when True."},{line:6,th:"else ทำงานเมื่อ False เท่านั้น",en:"else runs only when False."}],activityPath:[{phase:"worked",th:"ลอง 9/10/11 กับ >=10",en:"Try 9/10/11 with >=10."},{phase:"guided",th:"เปลี่ยน threshold 15 ทดสอบ 14/15/16",en:"Change threshold 15, test 14/15/16."},{phase:"independent",th:">=8 ทดสอบ 7/8/9",en:">=8 test 7/8/9."},{phase:"transfer",th:"==8 ทดสอบ 7/8/9",en:"==8 test 7/8/9."},{phase:"debug",th:"แก้ > vs >= และ indentation",en:"Fix > vs >= and indentation."}],scaffold:{th:["ดู branch diagram","ใช้กรณีเท่ากับ threshold เป็นตัวจับบั๊ก","ตรวจ colon และ 4 spaces"],en:["Use the branch diagram","Use equality boundary to catch bugs","Check colon and four spaces"]},stretch:{th:"เลือก threshold ใหม่แล้วออกแบบ below/equal/above tests",en:"Choose a new threshold and design below/equal/above tests."},debugTask:{code:'score = int(input(\"Score: \"))\nif score >= 8:\nprint(\"BONUS OPEN\")\nelse:\n    print(\"PRACTICE READY\")',promptTh:"print ใน if ไม่เยื้อง เกิด IndentationError",promptEn:"The print in if is not indented, causing IndentationError."},rubricAnchors:{behavior:"2 = correct 7/8/9 results for >= and == variations.",change:"2 = threshold/equality changed intentionally.",explain:"2 = explains equality and = versus ==.",debug:"2 = boundary/indent test reveals and fixes bug."}},
lesson05:{lineExplanations:[{line:1,th:"score เริ่มก่อน loop เพื่อสะสม",en:"score starts before the loop to accumulate."},{line:2,th:"range stop ไม่ถูกรวม",en:"range stop is excluded."},{line:3,th:"score update อยู่ใน loop จึงเกิดทุกรอบ",en:"score update is inside the loop, so it happens each round."},{line:5,th:"Final อยู่นอก loop จึงพิมพ์ครั้งเดียว",en:"Final is outside the loop, so it prints once."}],activityPath:[{phase:"worked",th:"trace 3 รอบ รอบละ 2 คะแนน",en:"Trace three rounds at two points each."},{phase:"guided",th:"เปลี่ยนเป็น 4 รอบ รอบละ 3 คะแนน",en:"Change to four rounds at three points each."},{phase:"independent",th:"สร้าง 5 รอบ รอบละ 2 คะแนน Final 10",en:"Create five rounds at two points each; Final 10."},{phase:"debug",th:"จับ reset-in-loop และ range(1,5) off-by-one",en:"Catch reset-inside-loop and range(1,5) off-by-one."}],scaffold:{th:["trace table หนึ่งแถวต่อรอบ","แยก round_number จากจำนวนรอบ","ขีดเส้นแยกนอก loop"],en:["One trace-table row per round","Separate round_number from count","Draw a line for outside the loop"]},stretch:{th:"ทำนายรอบ/คะแนนชุดใหม่โดยไม่ copy print ซ้ำ",en:"Predict a new round/point case without copying print blocks."},debugTask:{code:'score = 0\nfor round_number in range(1, 6):\n    score = 0\n    score = score + 2\n    print(\"Round\", round_number, \"Score\", score)\nprint(\"Final\", score)',promptTh:"score = 0 อยู่ใน loop จึงล้างคะแนนทุกรอบ",promptEn:"score = 0 is inside the loop, so it resets every round."},rubricAnchors:{behavior:"2 = correct count, scores, and one Final.",change:"2 = rounds/points changed intentionally.",explain:"2 = explains exclusive stop and outside-loop Final.",debug:"2 = catches reset/off-by-one with tests."}},
lesson07:{lineExplanations:[{line:1,th:"define show_score ก่อนเรียกใช้",en:"Define show_score before calling it."},{line:4,th:"score อยู่ก่อน loop เพื่อสะสมสามรอบ",en:"score is before loop to accumulate across three rounds."},{line:5,th:"for สร้าง 3 rounds",en:"for creates three rounds."},{line:10,th:"if answer == correct เลือก Hit หรือ Try again",en:"if answer == correct chooses Hit or Try again."},{line:14,th:"show_score แสดงคะแนนปัจจุบันหลังแต่ละรอบ",en:"show_score displays current score after each round."}],activityPath:[{phase:"worked",th:"trace mixed input 2,0,6",en:"Trace mixed input 2,0,6."},{phase:"guided",th:"เปลี่ยน points per correct answer เป็น 2",en:"Change points per correct answer to 2."},{phase:"independent",th:"ทดสอบ all-correct/all-wrong/mixed ได้ 6/0/4",en:"Test all-correct/all-wrong/mixed for 6/0/4."},{phase:"debug",th:"แก้ score reset หรือ indentation ด้วย counterexample",en:"Fix score reset or indentation with a counterexample."}],scaffold:{th:["ใช้ป้ายกำกับ block nesting","เขียน intermediate score ก่อนรัน","เรียก if ใน for ว่า composition ไม่ใช่ nested loop"],en:["Use block nesting labels","Write intermediate scores before running","Call if inside for composition, not nested loop"]},stretch:{th:"ให้เพื่อนเสนอ mixed case ใหม่แล้วทำนายคะแนนทุกจุด",en:"Have a peer propose a new mixed case and predict every score."},debugTask:{code:'score = 0\nfor round_number in range(1, 4):\n    score = 0\n    print(\"Round\", round_number)\n    answer = int(input(\"Round number x 2 = \"))\n    correct = round_number * 2\n    if answer == correct:\n        score = score + 2\n    print(\"Score:\", score)',promptTh:"score reset ใน loop ทำให้คะแนนไม่สะสม",promptEn:"score resets inside the loop, so it does not accumulate."},rubricAnchors:{behavior:"2 = three rounds and 6/0/4 final scores after remix.",change:"2 = scoring rule changed to two points.",explain:"2 = explains wrong answer leaves score unchanged.",debug:"2 = counterexample exposes and clears bug."}},
lesson08:{lineExplanations:[{line:1,th:"ใช้ Session 7 game เป็นฐานเมื่อมีหลักฐานเดิม",en:"Use the Session 7 game as base when prior evidence exists."},{line:3,th:"ชื่อเกม/avatar เป็น fiction ไม่ใช่ข้อมูลจริง",en:"Game/avatar names are fictional, not real personal data."},{line:5,th:"multiplier หรือ points คือ behavior change จริง",en:"multiplier or points is the real behavior change."},{line:10,th:"correct ต้องใช้กติกาที่เลือก",en:"correct must use the chosen rule."}],activityPath:[{phase:"review",th:"เปิดเกมเดิมและเลือกเป้าหมาย",en:"Open the existing game and choose a goal."},{phase:"plan",th:"เลือก multiplier 2–4 หรือ points 1–3",en:"Choose multiplier 2-4 or points 1-3."},{phase:"build",th:"ปรับข้อความ fiction และกติกา",en:"Customize fictional messages and rule."},{phase:"test",th:"รัน all-correct/all-wrong/mixed ตามกติกา",en:"Run all-correct/all-wrong/mixed for the rule."},{phase:"showcase",th:"My game is… This test shows… I fixed…",en:"My game is... This test shows... I fixed..."}],scaffold:{th:["คง 3 rounds ถ้ายังไม่มั่นใจ","เปลี่ยนกติกาเดียวก่อน","อัปเดต expected tests ให้ตรง"],en:["Keep three rounds if unsure","Change one rule first","Update expected tests to match"]},stretch:{th:"เพิ่มเป็น 3–5 rounds เฉพาะเมื่อคำอธิบายและ tests ตรงกัน",en:"Use 3-5 rounds only when instructions and tests match."},debugTask:{code:'multiplier = 3\ncorrect = round_number * 2',promptTh:"ถ้าเปลี่ยน multiplier แต่ correct ยังใช้ 2 tests จะจับได้",promptEn:"If multiplier changes but correct still uses 2, tests should catch it."},rubricAnchors:{behavior:"2 = all minimum game rules pass three test patterns.",change:"2 = real scoring/question rule changed.",explain:"2 = follows data to comparison to score.",debug:"2 = documents three patterns and one verified fix."}}
};

for (const [id, patch] of Object.entries(EXPLICIT_LESSON_PATCHES)) Object.assign(window.PP_LESSONS.find(l => l.id === id), patch);

for (const l of window.PP_LESSONS) {
  for (const field of ["lineExplanations","activityPath","scaffold","stretch","debugTask","rubricAnchors"]) {
    if (!l[field]) console.error(`Missing required lesson field ${field} for ${l.id}`);
  }
}
